# Generated by Django 4.2.5 on 2023-11-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='correo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='documento',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='rolempleado',
            name='tipo_rol',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='correo',
            field=models.CharField(max_length=50),
        ),
    ]
