# Generated by Django 4.2.5 on 2023-11-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_vehiculo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
