# Generated by Django 4.2.5 on 2023-11-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repuestoe',
            fields=[
                ('id_repuesto', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
    ]
