# Generated by Django 4.2.5 on 2023-11-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repuestoe',
        ),
    ]
